- name: install apache and php for Ubuntu servers
  tags: apache, apache2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start httpd ubuntu
  tags: apache, apache2, ubuntu
  service:
    name: apache2
    state: started
    enabled: yes  
  when: ansible_distribution == "Ubuntu"

- name: copy default html for site
  tags: apache, apache2, ubuntu
  copy:
    src: defaults_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: install apache and php for CentOS servers
  tags: apache, apache2, httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"
