# added the ssh key for that user simone
# task book!
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDVWW8MvCqFILl8XuxXT9Hh+Sn0dNKEH8ADr+/Bu4pGp ansible"

  - name: generate sshd_config file from template 
    tags: ssh
    template: 
      src: "{{ ssh_template_file }}"
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
    notify: restart_sshd
